[server]
# Grafana is behind Nginx, so tell it about the sub-path
root_url = https://grafana.exab-web.com/grafana/
serve_from_sub_path = true
protocol = http                  # Grafana itself runs plain HTTP
enforce_domain = false           # don't let Grafana do its own redirects

[security]
# These are overridden by the env vars in compose, but set safe defaults
admin_user     = admin
admin_password = 8wdLx6nS9HiL6PI5ciXl2bM3l     ; override  GF_SECURITY_ADMIN_PASSWORD

disable_gravatar         = true
cookie_secure            = true      ; set to false if running HTTP-only locally
cookie_samesite          = lax
strict_transport_security = true    ; set true when HTTPS is active
x_content_type_options   = true
x_xss_protection         = true
content_security_policy  = true

# Prevent embedding in iframes from other origins
allow_embedding = false

[users]
allow_sign_up        = false
allow_org_create     = false
auto_assign_org      = true
auto_assign_org_role = Viewer     ; default role for new users (if you ever add LDAP)

[auth.anonymous]
enabled = false

[auth]
disable_login_form  = false
oauth_auto_login    = false

[snapshots]
external_enabled = false           ; don't allow sharing snapshots to snapshot.raintank.io

[analytics]
reporting_enabled    = false
check_for_updates    = false

[log]
mode  = console
level = warn