apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: abdosaad0/webapp:latest

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: eshop-config

          env:
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: eshop-config
                  key: PUBLIC_IDENTITY_URL

            - name: CallBackUrl
              valueFrom:
                configMapKeyRef:
                  name: eshop-config
                  key: WEBAPP_CALLBACK_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: eshop
spec:
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
        - name: webhooksclient
          image: abdosaad0/webhooksclient:latest

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: eshop-config

          env:
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: eshop-config
                  key: PUBLIC_IDENTITY_URL

            - name: CallBackUrl
              valueFrom:
                configMapKeyRef:
                  name: eshop-config
                  key: WEBHOOKS_CALLBACK_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: webhooksclient
  namespace: eshop
spec:
  selector:
    app: webhooksclient
  ports:
    - port: 8080
      targetPort: 8080