apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: eshop

spec:
  ingressClassName: traefik

  rules:

    - host: shop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 8080

    - host: identity.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-api
                port:
                  number: 8080

    - host: webhooks.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhooksclient
                port:
                  number: 8080