apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: eshop
  annotations:
    # AWS Load Balancer Controller (EKS)
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/ID
spec:
  rules:
    - host: shop.eshop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 8080
    - host: identity.eshop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-api
                port:
                  number: 8080
    - host: webhooks.eshop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhooksclient
                port:
                  number: 8080
